[build]
  command = ""
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  force = true
  from = "/index"
  to = "/index.html"
  status = 301

[[redirects]]
  force = true
  from = "/*"
  to = "/index.html"
  status = 404